/**
 * Hand-written declaration for the vendored anti-slop plugin bundle
 * (plugin.mjs). The bundle is generated by scripts/vendor-anti-slop.ts; this
 * file only describes the plugin object shape oxlint consumes.
 */
declare const antiSlopPlugin: {
  meta: { name: string };
  rules: Record<string, unknown>;
};

export default antiSlopPlugin;
