export interface Agent {
  id: string;
  name: string;
}

export const agents: Agent[] = [
  { id: "claude", name: "Claude Code" },
  { id: "codex", name: "Codex" },
  { id: "jules", name: "Jules" },
  { id: "replit", name: "Replit Agent" },
  { id: "devin", name: "Devin" },
  { id: "lovable", name: "Lovable" },
  { id: "zencoder", name: "Zencoder" },
  { id: "ona", name: "Ona" },
  { id: "openclaw", name: "OpenClaw" },
  { id: "continue", name: "Continue" },
  { id: "snowflake-cortex", name: "Snowflake Cortex" },
  { id: "deepagents", name: "Deepagents" },
  { id: "qoder", name: "Qoder" },
  { id: "kimi-cli", name: "Kimi CLI" },
  { id: "mcpjam", name: "MCPJam" },
  { id: "mux", name: "Mux" },
  { id: "pi", name: "Pi" },
  { id: "adal", name: "AdaL" },
  { id: "copilot", name: "GitHub Copilot" },
  { id: "cline", name: "Cline" },
  { id: "amp", name: "AMP" },
  { id: "aider", name: "Aider" },
  { id: "firebase-studio", name: "Firebase Studio" },
  { id: "open-hands", name: "OpenHands" },
  { id: "gemini", name: "Gemini" },
  { id: "junie", name: "Junie" },
  { id: "augmentcode", name: "Augment Code" },
  { id: "bob", name: "IBM Bob" },
  { id: "kilo-code", name: "Kilo Code" },
  { id: "goose", name: "Goose" },
  { id: "roo-code", name: "Roo Code" },
  { id: "warp", name: "Warp" },
  { id: "droid", name: "Droid" },
  { id: "opencode", name: "OpenCode" },
  { id: "crush", name: "Crush" },
  { id: "qwen", name: "Qwen Code" },
  { id: "amazon-q-cli", name: "Amazon Q CLI" },
  { id: "firebender", name: "Firebender" },
  { id: "cursor-cli", name: "Cursor CLI" },
  { id: "mistral-vibe", name: "Mistral Vibe" },
  { id: "vercel", name: "Vercel Agent" },
];
