import type { PackageManagerName } from "nypm";

import { supportedPackageManagers } from "../package-manager";

/**
 * How each package manager runs a binary installed in the project. The
 * dlx-style runners init used to write (`pnpm dlx`, `yarn dlx`) download the
 * latest release from the registry instead of using the version the project
 * pins, and `yarn dlx` does not exist in Yarn 1 at all, so every commit failed
 * there. These all resolve `node_modules/.bin` first.
 */
const localBinRunners: Record<PackageManagerName, readonly string[]> = {
  aube: ["aube", "exec"],
  bun: ["bunx"],
  deno: ["deno", "run", "-A"],
  npm: ["npx"],
  nub: ["nub", "exec"],
  pnpm: ["pnpm", "exec"],
  yarn: ["yarn"],
};

/**
 * The command line that runs `bin` from the project's own dependencies, e.g.
 * `pnpm exec ultracite fix` or `yarn lint-staged`. Deno has no local-bin
 * runner, so it runs the npm package through its `npm:` specifier.
 */
export const localBinCommand = (
  packageManager: PackageManagerName,
  bin: string,
  args: string[] = []
): string => {
  const target = packageManager === "deno" ? `npm:${bin}` : bin;
  return [...localBinRunners[packageManager], target, ...args].join(" ");
};

/** `ultracite fix` run from the project's installed ultracite. */
export const ultraciteFixCommand = (
  packageManager: PackageManagerName
): string => localBinCommand(packageManager, "ultracite", ["fix"]);

// The dlx commands earlier versions of init wrote into git-hook configs
// (nypm's dlxCommand, short form for npm only), spelled out rather than
// recomputed so they stay fixed whatever nypm prints in future.
const legacyUltraciteFixCommands = [
  "aube dlx ultracite fix",
  "bun x ultracite fix",
  "deno run -A npm:ultracite fix",
  "npx ultracite fix",
  "nub dlx ultracite fix",
  "pnpm dlx ultracite fix",
  "pnpx ultracite fix",
  "yarn dlx ultracite fix",
];

/**
 * Every `ultracite fix` command an earlier `init` may have written into a
 * git-hook config, plus the current local-bin forms. Only exact matches
 * count, so a command a user wrote by hand is never rewritten.
 */
const generatedUltraciteFixCommands = (): ReadonlySet<string> =>
  new Set([
    ...legacyUltraciteFixCommands,
    ...supportedPackageManagers.map((packageManager) =>
      ultraciteFixCommand(packageManager)
    ),
  ]);

/**
 * Whether `command` is an `ultracite fix` command generated by this or an
 * earlier `init`, and so safe to replace with the current one.
 */
export const isGeneratedUltraciteFixCommand = (command: string): boolean =>
  generatedUltraciteFixCommands().has(command.trim());

// Matches any command that runs `ultracite fix`, however it is invoked.
const ULTRACITE_FIX_RE = /(?:^|[\s:/])ultracite\s+fix\b/u;

/** Whether a hook command already runs `ultracite fix` in some form. */
export const runsUltraciteFix = (command: string): boolean =>
  ULTRACITE_FIX_RE.test(command);

/**
 * `existing` with `command` appended, for package.json lifecycle scripts such
 * as `prepare` that several tools want to own. A script that already runs the
 * tool (matched by `alreadyRuns`) is kept as it is.
 */
export const chainScript = (
  existing: string | undefined,
  command: string,
  alreadyRuns: RegExp
): string => {
  const trimmed = existing?.trim();

  if (!trimmed) {
    return command;
  }

  if (alreadyRuns.test(trimmed)) {
    return trimmed;
  }

  return `${trimmed} && ${command}`;
};
