import { describe, expect, test } from "bun:test";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

import { supportsNativeNodeTypeScriptConfig } from "../src/path-config-adapters";

const fixture = path.join(import.meta.dir, "fixtures", "path-config");
const nativeOxlintFixture = path.join(fixture, "native-oxlint");
const cliRoot = path.resolve(import.meta.dir, "..");
const cliEntry = path.join(cliRoot, "src", "path-config.ts");
const adapterEntry = path.join(cliRoot, "src", "path-config-adapters.ts");
const jitiRegister = pathToFileURL(
  path.join(cliRoot, "node_modules", "jiti", "lib", "jiti-register.mjs")
).href;
const biomeBin = path.join(
  cliRoot,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "biome.exe" : "biome"
);

describe("path-scoped provider configs", () => {
  test("recognizes Node versions that can load native TypeScript configs", () => {
    expect(supportsNativeNodeTypeScriptConfig("20.18.0")).toBe(false);
    expect(supportsNativeNodeTypeScriptConfig("20.19.0")).toBe(true);
    expect(supportsNativeNodeTypeScriptConfig("21.7.3")).toBe(false);
    expect(supportsNativeNodeTypeScriptConfig("22.17.0")).toBe(false);
    expect(supportsNativeNodeTypeScriptConfig("22.18.0")).toBe(true);
    expect(supportsNativeNodeTypeScriptConfig("23.5.0")).toBe(false);
    expect(supportsNativeNodeTypeScriptConfig("23.6.0")).toBe(true);
    expect(supportsNativeNodeTypeScriptConfig("24.0.0")).toBe(true);
  });

  test("Biome and ESLint native outputs retain the directory scope", async () => {
    const generated = Bun.spawnSync(
      [
        "bun",
        "-e",
        `import { resolvePathConfig } from ${JSON.stringify(cliEntry)}; import { materializePathConfig } from ${JSON.stringify(adapterEntry)}; const root = process.cwd(); const config = await resolvePathConfig(root, [root + "/ultracite.config.ts", root + "/apps/web/ultracite.config.ts"]); await materializePathConfig("biome", config); await materializePathConfig("eslint", config);`,
      ],
      { cwd: fixture }
    );
    expect(generated.exitCode).toBe(0);

    // SAFETY: This is generated by the Biome adapter immediately above in the child process.
    const biomeConfig = JSON.parse(
      await Bun.file(
        path.join(fixture, "node_modules/.cache/ultracite/biome.json")
      ).text()
    ) as { overrides: { includes?: string[] }[] };
    const eslint = await Bun.file(
      path.join(fixture, "node_modules/.cache/ultracite/eslint.config.mjs")
    ).text();

    expect(
      biomeConfig.overrides.some(
        (override) =>
          override.includes?.some((file) => file.startsWith("apps/web/")) &&
          !override.includes.some((file) => file.startsWith("packages/shared/"))
      )
    ).toBe(true);
    expect(eslint).toContain("apps/web/**/*");
    expect(eslint).toContain('scopeConfig(preset0, ["**/*","!apps/web/**/*"])');
    expect(eslint).toContain("export default");

    const lint = Bun.spawnSync(
      [
        biomeBin,
        "check",
        "--config-path=node_modules/.cache/ultracite/biome.json",
        "--no-errors-on-unmatched",
        "apps/web/src/bad-component.tsx",
        "apps/docs/src/bad-component.tsx",
        "packages/shared/src/bad-component.tsx",
        "packages/shared/src/native-rule.ts",
      ],
      { cwd: fixture }
    );
    const output = `${lint.stdout.toString()}${lint.stderr.toString()}`;
    expect(lint.exitCode).toBe(1);
    expect(output).toContain("useButtonType");
    const normalizedOutput = output.replaceAll("\\", "/");
    expect(normalizedOutput).toContain("apps/web/src/bad-component.tsx");
    expect(normalizedOutput).not.toContain("apps/docs/src/bad-component.tsx:");
    expect(normalizedOutput).not.toContain(
      "packages/shared/src/bad-component.tsx:"
    );
  });

  test("Oxlint keeps its native TypeScript config alongside Ultracite path config", () => {
    const materialize = Bun.spawnSync(
      [
        process.execPath,
        "-e",
        `import { readFileSync, rmSync } from "node:fs"; import path from "node:path"; import { resolvePathConfig } from ${JSON.stringify(cliEntry)}; import { materializePathConfig } from ${JSON.stringify(adapterEntry)}; const root = process.cwd(); const output = path.join(root, ".ultracite-oxlint.config.mjs"); try { const config = await resolvePathConfig(root, [path.join(root, "ultracite.config.ts")]); await materializePathConfig("oxlint", config); console.log(readFileSync(output, "utf-8")); } finally { rmSync(output, { force: true }); }`,
      ],
      { cwd: nativeOxlintFixture }
    );
    if (materialize.exitCode !== 0) {
      throw new Error(materialize.stderr.toString());
    }
    const oxlintConfig = materialize.stdout.toString();
    expect(oxlintConfig).toContain("oxlint.config.ts");
    expect(oxlintConfig).toContain('"no-console":"error"');
    expect(oxlintConfig).toContain('"react"');
    expect(oxlintConfig).toContain('"native-generated/**"');
    expect(oxlintConfig).toContain('"packages/shared/src/**/*.ts"');
  });

  test("root check and fix materialize the shared DSL for explicit cross-scope files", () => {
    const runCommands = Bun.spawnSync(
      [
        process.execPath,
        "-e",
        `import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs"; import { spawnSync } from "node:child_process"; import path from "node:path"; const root = process.cwd(); const files = [path.join(root, "apps/web/package.json"), path.join(root, ".oxlintrc.json"), path.join(root, "apps/web/src/clean.ts"), path.join(root, "packages/shared/src/clean.ts"), path.join(root, ".ultracite-oxlint.config.mjs")]; const originals = new Map(files.map((file) => [file, existsSync(file) ? readFileSync(file) : undefined])); try { const [manifest, nativeConfig, webFile, sharedFile] = files; writeFileSync(nativeConfig, JSON.stringify({ rules: { "no-alert": "error" } })); writeFileSync(manifest, "{}\\n"); writeFileSync(webFile, "export const clean = 1;\\n"); writeFileSync(sharedFile, "export const clean = 1;\\n"); const cli = ${JSON.stringify(path.join(cliRoot, "src", "index.ts"))}; const env = { ...process.env, NODE_OPTIONS: [process.env.NODE_OPTIONS, "--import=${jitiRegister}"].filter(Boolean).join(" "), PATH: ${JSON.stringify(path.join(cliRoot, "node_modules", ".bin"))} + path.delimiter + process.env.PATH }; const check = spawnSync(process.execPath, [cli, "check", "--format=unix", "apps/web/src/clean.ts", "packages/shared/src/clean.ts"], { cwd: root, encoding: "utf-8", env }); const fix = spawnSync(process.execPath, [cli, "fix", "--format=unix", "apps/web/src/clean.ts", "packages/shared/src/clean.ts"], { cwd: root, encoding: "utf-8", env }); console.log(JSON.stringify({ checkStatus: check.status, checkOutput: check.stdout + check.stderr, fixStatus: fix.status, fixOutput: fix.stdout + fix.stderr })); } finally { for (const [file, contents] of originals) { if (contents === undefined) rmSync(file, { force: true }); else writeFileSync(file, contents); } }`,
      ],
      { cwd: fixture }
    );
    if (runCommands.exitCode !== 0) {
      throw new Error(
        `${runCommands.stdout.toString()}${runCommands.stderr.toString()}`
      );
    }
    // SAFETY: The subprocess prints the result object constructed in the inline integration script.
    const result = JSON.parse(runCommands.stdout.toString()) as {
      checkOutput: string;
      checkStatus: number | null;
      fixOutput: string;
      fixStatus: number | null;
    };
    if (result.checkStatus !== 0) {
      throw new Error(
        `check exited ${result.checkStatus}: ${result.checkOutput}`
      );
    }
    if (result.fixStatus !== 0) {
      throw new Error(`fix exited ${result.fixStatus}: ${result.fixOutput}`);
    }
    expect(result.checkStatus).toBe(0);
    expect(result.fixStatus).toBe(0);
    expect(result.checkOutput).not.toContain("Could not resolve");
    expect(result.fixOutput).not.toContain("Could not resolve");
  });
});
