/**
 * Re-vendors the anti-slop oxlint plugin (https://github.com/dmmulroy/anti-slop)
 * into config/oxlint/anti-slop/plugin.mjs.
 *
 * anti-slop is deliberately not published to npm — upstream's distribution
 * model is "copy the source into your repo" — so Ultracite ships a bundled
 * build instead of declaring a dependency. The bundle inlines the plugin's
 * only dependency (@oxlint/plugins, a small pure-JS, dependency-free shim) so
 * the vendored file is fully self-contained.
 *
 * Usage: bun run scripts/vendor-anti-slop.ts [ref]
 *
 * Clones upstream at the pinned commit (or the given ref), installs its
 * dependencies, bundles src/index.ts to ESM, and rewrites plugin.mjs with an
 * attribution banner. After bumping PINNED_REF, review the upstream diff and
 * update the rules list in config/oxlint/anti-slop/index.mjs if rules were
 * added, removed, or renamed (the oxlint-config tests will catch a mismatch).
 */
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const REPO_URL = "https://github.com/dmmulroy/anti-slop.git";
const PINNED_REF = "e8c4880471b23ab7f216fba7b27d173a6ef07d4c";

const ref = process.argv[2] ?? PINNED_REF;
const outFile = path.join(
  import.meta.dirname,
  "../config/oxlint/anti-slop/plugin.mjs"
);

const run = (command: string[], cwd: string): string => {
  const result = Bun.spawnSync(command, { cwd, stderr: "inherit" });
  if (result.exitCode !== 0) {
    throw new Error(`${command.join(" ")} failed in ${cwd}`);
  }
  return result.stdout.toString().trim();
};

const cloneDir = mkdtempSync(path.join(tmpdir(), "anti-slop-"));

try {
  run(["git", "clone", REPO_URL, "."], cloneDir);
  run(["git", "checkout", ref], cloneDir);
  const commit = run(["git", "rev-parse", "HEAD"], cloneDir);

  // Install the plugin's dependencies (just @oxlint/plugins) so the bundler
  // can inline them.
  run(["bun", "install", "--production"], cloneDir);

  const build = await Bun.build({
    entrypoints: [path.join(cloneDir, "src/index.ts")],
    format: "esm",
    target: "node",
  });

  if (!(build.success && build.outputs.length === 1)) {
    throw new Error(
      `Bundling anti-slop failed: ${build.logs.map(String).join("\n")}`
    );
  }

  // Bun emits a `// <path>` comment per bundled module, relative to the
  // output location — which points into the temp clone dir and differs per
  // machine. Trim the prefix so re-vendoring produces stable diffs.
  const cloneDirPattern = new RegExp(
    `^// \\S*${path.basename(cloneDir)}/`,
    "gmu"
  );
  const rawBundle = await build.outputs[0].text();
  const bundle = rawBundle.replace(cloneDirPattern, "// ");
  const banner = `// Vendored build of the anti-slop oxlint plugin.
// Source: https://github.com/dmmulroy/anti-slop (MIT) at commit ${commit}.
// Its @oxlint/plugins dependency (MIT) is inlined so this file is
// self-contained. See license.md for the full license texts.
//
// Generated by scripts/vendor-anti-slop.ts — do not edit by hand.
`;

  writeFileSync(outFile, banner + bundle);
  console.log(`Vendored anti-slop@${commit} to ${outFile}`);
} finally {
  rmSync(cloneDir, { force: true, recursive: true });
}
