import { defineConfig } from "oxlint";

// eslint-plugin-github, eslint-plugin-sonarjs, and oxlint-plugin-react-doctor
// run through oxlint's JS plugin support to close the gap with the ESLint
// preset and to add React Doctor's extra checks. This preset is opt-in: extend
// it alongside core (and any framework preset) only when you want those rules
// and accept the extra dependencies plus the slower JS-plugin lint pass. Rules
// that require type information are not supported by the JS plugin bridge and
// are excluded. The react-doctor rules were previously bundled into the
// react/next/tanstack presets; they live here now so those framework presets
// run entirely on oxlint's native Rust rules.
//
// Install the plugins in your project, then extend the preset:
//
//   npm install -D eslint-plugin-github eslint-plugin-sonarjs oxlint-plugin-react-doctor
//
//   import { defineConfig } from "oxlint";
//   import core from "ultracite/oxlint/core";
//   import jsPlugins from "ultracite/oxlint/js-plugins";
//
//   export default defineConfig({
//     extends: [core, jsPlugins],
//     ignorePatterns: core.ignorePatterns,
//   });
export default defineConfig({
  jsPlugins: [
    { name: "github", specifier: "eslint-plugin-github" },
    { name: "sonarjs", specifier: "eslint-plugin-sonarjs" },
    { name: "react-doctor", specifier: "oxlint-plugin-react-doctor" },
  ],
  overrides: [
    {
      files: [
        "**/*.{test,spec}.{ts,tsx,js,jsx}",
        "**/__tests__/**/*.{ts,tsx,js,jsx}",
      ],
      rules: {
        // Repeated string literals (test titles, expected values) are normal
        // and idiomatic in test files.
        "sonarjs/no-duplicate-string": "off",
      },
    },
  ],
  rules: {
    // ── github ─────────────────────────────────────────────────────────
    "github/a11y-aria-label-is-well-formatted": "error",
    "github/a11y-no-title-attribute": "error",
    "github/a11y-no-visually-hidden-interactive-element": "error",
    "github/a11y-role-supports-aria-props": "error",
    "github/a11y-svg-has-accessible-name": "error",
    "github/array-foreach": "error",
    "github/async-currenttarget": "error",
    "github/async-preventdefault": "error",
    "github/authenticity-token": "error",
    "github/filenames-match-regex": "error",
    "github/get-attribute": "error",
    "github/js-class-name": "error",
    "github/no-blur": "error",
    "github/no-d-none": "error",
    // Conflicts with unicorn/prefer-dom-node-dataset, which is the benchmark.
    "github/no-dataset": "off",
    "github/no-dynamic-script-tag": "error",
    // The JS plugin bridge misreads module-scoped declarations (e.g. Astro
    // frontmatter) as implicit globals, producing false positives.
    "github/no-implicit-buggy-globals": "off",
    "github/no-inner-html": "error",
    "github/no-innerText": "error",
    "github/no-then": "error",
    "github/no-useless-passive": "error",
    "github/prefer-observers": "error",
    "github/require-passive-events": "error",
    // Mirrors the ESLint preset.
    "github/unescaped-html-literal": "off",

    // ── sonarjs ────────────────────────────────────────────────────────
    // These sonarjs rules exist in eslint-plugin-sonarjs but oxlint's JS
    // plugin bridge does not register them, so listing them fails config
    // parsing. They are intentionally omitted here (still enabled in the
    // ESLint preset): async-test-assertions, hooks-before-test-cases,
    // no-duplicate-test-title, no-empty-test-title, no-floating-point-equality,
    // no-forced-browser-interaction, no-trivial-assertions,
    // prefer-specific-assertions, super-linear-regex.
    "sonarjs/arguments-usage": "error",
    "sonarjs/array-constructor": "error",
    // Fights the formatter (arrowParentheses: always).
    "sonarjs/arrow-function-convention": "off",
    "sonarjs/aws-apigateway-public-api": "error",
    "sonarjs/aws-ec2-rds-dms-public": "error",
    "sonarjs/aws-ec2-unencrypted-ebs-volume": "error",
    "sonarjs/aws-efs-unencrypted": "error",
    "sonarjs/aws-iam-all-privileges": "error",
    "sonarjs/aws-iam-all-resources-accessible": "error",
    "sonarjs/aws-iam-privilege-escalation": "error",
    "sonarjs/aws-iam-public-access": "error",
    "sonarjs/aws-opensearchservice-domain": "error",
    "sonarjs/aws-rds-unencrypted-databases": "error",
    "sonarjs/aws-restricted-ip-admin-access": "error",
    "sonarjs/aws-s3-bucket-granted-access": "error",
    "sonarjs/aws-s3-bucket-insecure-http": "error",
    "sonarjs/aws-s3-bucket-public-access": "error",
    "sonarjs/aws-s3-bucket-versioning": "error",
    "sonarjs/aws-sagemaker-unencrypted-notebook": "error",
    "sonarjs/aws-sns-unencrypted-topics": "error",
    "sonarjs/aws-sqs-unencrypted-queue": "error",
    "sonarjs/block-scoped-var": "error",
    "sonarjs/bool-param-default": "error",
    "sonarjs/call-argument-line": "error",
    "sonarjs/chai-determinate-assertion": "error",
    "sonarjs/class-name": "error",
    "sonarjs/code-eval": "error",
    // Matches Biome's noExcessiveCognitiveComplexity limit.
    "sonarjs/cognitive-complexity": ["error", 20],
    "sonarjs/comma-or-logical-or-case": "error",
    "sonarjs/comment-regex": "error",
    "sonarjs/constructor-for-side-effects": "error",
    "sonarjs/content-length": "error",
    "sonarjs/content-security-policy": "error",
    "sonarjs/cookie-no-httponly": "error",
    "sonarjs/cors": "error",
    "sonarjs/csrf": "error",
    // Duplicate of the core complexity rule.
    "sonarjs/cyclomatic-complexity": "off",
    "sonarjs/declarations-in-global-scope": "error",
    "sonarjs/destructuring-assignment-syntax": "error",
    "sonarjs/disabled-timeout": "error",
    "sonarjs/dynamically-constructed-templates": "error",
    // Mirrors the ESLint preset.
    "sonarjs/elseif-without-else": "off",
    "sonarjs/encryption-secure-mode": "error",
    "sonarjs/expression-complexity": "error",
    // Requires a headerFormat option; errors on every file without one.
    "sonarjs/file-header": "off",
    // Fires on any file whose name differs from an exported class, which is
    // noise for config and module files that export objects, not classes.
    "sonarjs/file-name-differ-from-class": "off",
    "sonarjs/file-permissions": "error",
    "sonarjs/file-uploads": "error",
    "sonarjs/fixme-tag": "error",
    "sonarjs/for-in": "error",
    "sonarjs/for-loop-increment-sign": "error",
    "sonarjs/function-inside-loop": "error",
    "sonarjs/function-name": "error",
    "sonarjs/future-reserved-words": "error",
    "sonarjs/generator-without-yield": "error",
    "sonarjs/hardcoded-secret-signatures": "error",
    "sonarjs/hashing": "error",
    "sonarjs/inconsistent-function-call": "error",
    "sonarjs/insecure-cookie": "error",
    "sonarjs/insecure-jwt-token": "error",
    "sonarjs/inverted-assertion-arguments": "error",
    "sonarjs/label-position": "error",
    "sonarjs/link-with-target-blank": "error",
    // The preset disables max-lines everywhere.
    "sonarjs/max-lines": "off",
    // The preset disables max-lines-per-function everywhere.
    "sonarjs/max-lines-per-function": "off",
    "sonarjs/max-switch-cases": "error",
    "sonarjs/max-union-size": "error",
    "sonarjs/misplaced-loop-counter": "error",
    // Duplicate of max-depth, which is off.
    "sonarjs/nested-control-flow": "off",
    "sonarjs/no-all-duplicated-branches": "error",
    "sonarjs/no-angular-bypass-sanitization": "error",
    "sonarjs/no-built-in-override": "error",
    "sonarjs/no-case-label-in-switch": "error",
    "sonarjs/no-clear-text-protocols": "error",
    "sonarjs/no-code-after-done": "error",
    "sonarjs/no-collapsible-if": "error",
    "sonarjs/no-commented-code": "error",
    "sonarjs/no-dead-store": "error",
    "sonarjs/no-delete-var": "error",
    "sonarjs/no-duplicate-in-composite": "error",
    "sonarjs/no-duplicate-string": "error",
    "sonarjs/no-duplicated-branches": "error",
    "sonarjs/no-element-overwrite": "error",
    "sonarjs/no-empty-collection": "error",
    "sonarjs/no-empty-test-file": "error",
    "sonarjs/no-equals-in-for-termination": "error",
    "sonarjs/no-exclusive-tests": "error",
    "sonarjs/no-extra-arguments": "error",
    "sonarjs/no-fallthrough": "error",
    "sonarjs/no-function-declaration-in-block": "error",
    "sonarjs/no-global-this": "error",
    "sonarjs/no-globals-shadowing": "error",
    "sonarjs/no-gratuitous-expressions": "error",
    "sonarjs/no-hardcoded-ip": "error",
    "sonarjs/no-hardcoded-passwords": "error",
    "sonarjs/no-hardcoded-secrets": "error",
    "sonarjs/no-hook-setter-in-body": "error",
    "sonarjs/no-identical-conditions": "error",
    "sonarjs/no-identical-expressions": "error",
    "sonarjs/no-identical-functions": "error",
    "sonarjs/no-ignored-exceptions": "error",
    // The JS plugin bridge has no dependency-manifest resolution, so this
    // flags builtin (bun:test) and workspace imports as missing dependencies.
    "sonarjs/no-implicit-dependencies": "off",
    "sonarjs/no-implicit-global": "error",
    "sonarjs/no-incomplete-assertions": "error",
    "sonarjs/no-internal-api-use": "error",
    "sonarjs/no-invariant-returns": "error",
    "sonarjs/no-inverted-boolean-check": "error",
    "sonarjs/no-labels": "error",
    "sonarjs/no-literal-call": "error",
    "sonarjs/no-mime-sniff": "error",
    "sonarjs/no-nested-assignment": "error",
    "sonarjs/no-nested-conditional": "error",
    "sonarjs/no-nested-functions": "error",
    "sonarjs/no-nested-incdec": "error",
    "sonarjs/no-nested-switch": "error",
    "sonarjs/no-nested-template-literals": "error",
    "sonarjs/no-os-command-from-path": "error",
    "sonarjs/no-parameter-reassignment": "error",
    "sonarjs/no-primitive-wrappers": "error",
    "sonarjs/no-redundant-assignments": "error",
    "sonarjs/no-redundant-boolean": "error",
    "sonarjs/no-redundant-jump": "error",
    // The jsPlugins bridge provides no globals, so every identifier is flagged.
    "sonarjs/no-reference-error": "off",
    "sonarjs/no-referrer-policy": "error",
    "sonarjs/no-same-argument-assert": "error",
    "sonarjs/no-same-line-conditional": "error",
    "sonarjs/no-session-cookies-on-static-assets": "error",
    "sonarjs/no-skipped-tests": "error",
    "sonarjs/no-sonar-comments": "error",
    "sonarjs/no-table-as-layout": "error",
    "sonarjs/no-undefined-assignment": "error",
    "sonarjs/no-unenclosed-multiline-block": "error",
    "sonarjs/no-uniq-key": "error",
    "sonarjs/no-unthrown-error": "error",
    "sonarjs/no-unused-collection": "error",
    "sonarjs/no-unused-function-argument": "error",
    "sonarjs/no-unused-vars": "error",
    "sonarjs/no-use-of-empty-return-value": "error",
    "sonarjs/no-useless-catch": "error",
    "sonarjs/no-useless-increment": "error",
    "sonarjs/no-useless-react-setstate": "error",
    "sonarjs/no-variable-usage-before-declaration": "error",
    "sonarjs/no-weak-cipher": "error",
    "sonarjs/no-weak-keys": "error",
    "sonarjs/no-wildcard-import": "error",
    "sonarjs/non-existent-operator": "error",
    "sonarjs/object-alt-content": "error",
    "sonarjs/prefer-default-last": "error",
    "sonarjs/prefer-object-literal": "error",
    "sonarjs/prefer-promise-shorthand": "error",
    "sonarjs/prefer-single-boolean-return": "error",
    "sonarjs/prefer-type-guard": "error",
    "sonarjs/prefer-while": "error",
    "sonarjs/production-debug": "error",
    "sonarjs/pseudo-random": "error",
    "sonarjs/public-static-readonly": "error",
    "sonarjs/publicly-writable-directories": "error",
    "sonarjs/redundant-type-aliases": "error",
    "sonarjs/review-blockchain-mnemonic": "error",
    "sonarjs/session-regeneration": "error",
    // Conflicts with sort-keys.
    "sonarjs/shorthand-property-grouping": "off",
    "sonarjs/stable-tests": "error",
    "sonarjs/stateful-regex": "error",
    "sonarjs/strict-transport-security": "error",
    "sonarjs/table-header": "error",
    "sonarjs/table-header-reference": "error",
    "sonarjs/test-check-exception": "error",
    "sonarjs/todo-tag": "error",
    "sonarjs/too-many-break-or-continue-in-loop": "error",
    "sonarjs/unverified-certificate": "error",
    "sonarjs/unverified-hostname": "error",
    "sonarjs/updated-const-var": "error",
    "sonarjs/updated-loop-counter": "error",
    "sonarjs/use-type-alias": "error",
    "sonarjs/variable-name": "error",
    "sonarjs/weak-ssl": "error",
    "sonarjs/x-powered-by": "error",
    "sonarjs/xml-parser-xxe": "error",

    // ── react-doctor ────────────────────────────────────────────────────
    // Generic React rules.
    "react-doctor/activity-wraps-effect-heavy-subtree": "error",
    "react-doctor/advanced-event-handler-refs": "error",
    "react-doctor/async-await-in-loop": "error",
    "react-doctor/async-defer-await": "error",
    "react-doctor/async-parallel": "error",
    "react-doctor/auth-token-in-web-storage": "error",
    "react-doctor/client-localstorage-no-version": "error",
    "react-doctor/client-passive-event-listeners": "error",
    "react-doctor/dialog-has-accessible-name": "error",
    "react-doctor/effect-needs-cleanup": "error",
    "react-doctor/hooks-no-nan-in-deps": "error",
    "react-doctor/html-no-invalid-paragraph-child": "error",
    "react-doctor/html-no-invalid-table-nesting": "error",
    "react-doctor/html-no-nested-interactive": "error",
    "react-doctor/jotai-derived-atom-returns-fresh-object": "error",
    "react-doctor/jotai-select-atom-in-render-body": "error",
    "react-doctor/jotai-tq-use-raw-query-atom": "error",
    "react-doctor/js-async-reduce-without-awaited-acc": "error",
    "react-doctor/js-batch-dom-css": "error",
    "react-doctor/js-cache-property-access": "error",
    "react-doctor/js-cache-storage": "error",
    "react-doctor/js-combine-iterations": "error",
    "react-doctor/js-early-exit": "error",
    "react-doctor/js-flatmap-filter": "error",
    "react-doctor/js-hoist-intl": "error",
    "react-doctor/js-hoist-regexp": "error",
    "react-doctor/js-index-maps": "error",
    "react-doctor/js-length-check-first": "error",
    "react-doctor/js-min-max-loop": "error",
    "react-doctor/js-set-map-lookups": "error",
    "react-doctor/js-tosorted-immutable": "error",
    "react-doctor/no-adjust-state-on-prop-change": "error",
    "react-doctor/no-array-index-as-key": "error",
    "react-doctor/no-async-effect-callback": "error",
    "react-doctor/no-barrel-import": "error",
    "react-doctor/no-call-component-as-function": "error",
    "react-doctor/no-cascading-set-state": "error",
    "react-doctor/no-chain-state-updates": "error",
    "react-doctor/no-create-context-in-render": "error",
    "react-doctor/no-create-ref-in-function-component": "error",
    "react-doctor/no-create-store-in-render": "error",
    "react-doctor/no-derived-state": "error",
    "react-doctor/no-derived-state-effect": "error",
    "react-doctor/no-derived-useState": "error",
    "react-doctor/no-direct-state-mutation": "error",
    "react-doctor/no-disabled-zoom": "error",
    "react-doctor/no-document-start-view-transition": "error",
    "react-doctor/no-document-write": "error",
    "react-doctor/no-dynamic-import-path": "error",
    "react-doctor/no-effect-chain": "error",
    "react-doctor/no-effect-event-handler": "error",
    "react-doctor/no-effect-event-in-deps": "error",
    "react-doctor/no-effect-with-fresh-deps": "error",
    "react-doctor/no-eval": "error",
    "react-doctor/no-event-handler": "error",
    "react-doctor/no-event-trigger-state": "error",
    "react-doctor/no-fetch-in-effect": "error",
    "react-doctor/no-flush-sync": "error",
    "react-doctor/no-full-lodash-import": "error",
    "react-doctor/no-giant-component": "error",
    "react-doctor/no-global-css-variable-animation": "error",
    "react-doctor/no-gray-on-colored-background": "error",
    "react-doctor/no-img-lazy-with-high-fetchpriority": "error",
    "react-doctor/no-initialize-state": "error",
    "react-doctor/no-inline-bounce-easing": "error",
    "react-doctor/no-inline-exhaustive-style": "error",
    "react-doctor/no-inline-prop-on-memo-component": "error",
    "react-doctor/no-json-parse-stringify-clone": "error",
    "react-doctor/no-jsx-element-type": "error",
    "react-doctor/no-large-animated-blur": "error",
    "react-doctor/no-layout-property-animation": "error",
    "react-doctor/no-layout-transition-inline": "error",
    "react-doctor/no-legacy-class-lifecycles": "error",
    "react-doctor/no-legacy-context-api": "error",
    "react-doctor/no-long-transition-duration": "error",
    "react-doctor/no-many-boolean-props": "error",
    "react-doctor/no-mirror-prop-effect": "error",
    "react-doctor/no-moment": "error",
    "react-doctor/no-mutable-in-deps": "error",
    "react-doctor/no-mutating-reducer-state": "error",
    "react-doctor/no-nested-component-definition": "error",
    "react-doctor/no-outline-none": "error",
    "react-doctor/no-pass-data-to-parent": "error",
    "react-doctor/no-pass-live-state-to-parent": "error",
    "react-doctor/no-permanent-will-change": "error",
    "react-doctor/no-polymorphic-children": "error",
    "react-doctor/no-prevent-default": "error",
    "react-doctor/no-prop-callback-in-effect": "error",
    "react-doctor/no-random-key": "error",
    "react-doctor/no-react-dom-deprecated-apis": "error",
    "react-doctor/no-react19-deprecated-apis": "error",
    "react-doctor/no-render-in-render": "error",
    "react-doctor/no-render-prop-children": "error",
    "react-doctor/no-reset-all-state-on-prop-change": "error",
    "react-doctor/no-scale-from-zero": "error",
    "react-doctor/no-secrets-in-client-code": "error",
    "react-doctor/no-self-updating-effect": "error",
    "react-doctor/no-set-state-in-render": "error",
    "react-doctor/no-string-false-on-boolean-attribute": "error",
    "react-doctor/no-sync-xhr": "error",
    "react-doctor/no-tiny-text": "error",
    "react-doctor/no-transition-all": "error",
    "react-doctor/no-uncontrolled-input": "error",
    "react-doctor/no-undeferred-third-party": "error",
    "react-doctor/no-usememo-simple-expression": "error",
    "react-doctor/only-export-components": "error",
    "react-doctor/prefer-dynamic-import": "error",
    "react-doctor/prefer-explicit-variants": "error",
    "react-doctor/prefer-html-dialog": "error",
    "react-doctor/prefer-module-scope-pure-function": "error",
    "react-doctor/prefer-module-scope-static-value": "error",
    "react-doctor/prefer-stable-empty-fallback": "error",
    "react-doctor/prefer-use-effect-event": "error",
    "react-doctor/prefer-use-sync-external-store": "error",
    "react-doctor/prefer-useReducer": "error",
    "react-doctor/react-compiler-no-manual-memoization": "error",
    "react-doctor/redux-useselector-inline-derivation": "error",
    "react-doctor/redux-useselector-returns-new-collection": "error",
    "react-doctor/rendering-animate-svg-wrapper": "error",
    "react-doctor/rendering-conditional-render": "error",
    "react-doctor/rendering-hoist-jsx": "error",
    "react-doctor/rendering-hydration-mismatch-time": "error",
    "react-doctor/rendering-hydration-no-flicker": "error",
    "react-doctor/rendering-script-defer-async": "error",
    "react-doctor/rendering-svg-precision": "error",
    "react-doctor/rendering-usetransition-loading": "error",
    "react-doctor/rerender-defer-reads-hook": "error",
    "react-doctor/rerender-dependencies": "error",
    "react-doctor/rerender-derived-state-from-hook": "error",
    "react-doctor/rerender-functional-setstate": "error",
    "react-doctor/rerender-lazy-ref-init": "error",
    "react-doctor/rerender-lazy-state-init": "error",
    "react-doctor/rerender-memo-before-early-return": "error",
    "react-doctor/rerender-memo-with-default-value": "error",
    "react-doctor/rerender-state-only-in-handlers": "error",
    "react-doctor/rerender-transitions-scroll": "error",
    "react-doctor/server-after-nonblocking": "error",
    "react-doctor/server-auth-actions": "error",
    "react-doctor/server-cache-with-object-literal": "error",
    "react-doctor/server-dedup-props": "error",
    "react-doctor/server-fetch-without-revalidate": "error",
    "react-doctor/server-hoist-static-io": "error",
    "react-doctor/server-no-mutable-module-state": "error",
    "react-doctor/server-sequential-independent-await": "error",
    "react-doctor/use-lazy-motion": "error",
    "react-doctor/zod-v4-no-deprecated-error-apis": "error",
    "react-doctor/zod-v4-no-deprecated-error-customization": "error",
    "react-doctor/zod-v4-no-deprecated-schema-apis": "error",
    "react-doctor/zod-v4-prefer-top-level-string-formats": "error",
    // Next.js rules.
    "react-doctor/nextjs-async-client-component": "error",
    "react-doctor/nextjs-error-boundary-missing-use-client": "error",
    "react-doctor/nextjs-global-error-missing-html-body": "error",
    "react-doctor/nextjs-image-missing-sizes": "error",
    "react-doctor/nextjs-inline-script-missing-id": "error",
    "react-doctor/nextjs-missing-metadata": "error",
    "react-doctor/nextjs-no-a-element": "error",
    "react-doctor/nextjs-no-client-fetch-for-server-data": "error",
    "react-doctor/nextjs-no-client-side-redirect": "error",
    "react-doctor/nextjs-no-css-link": "error",
    "react-doctor/nextjs-no-default-export-in-route-handler": "error",
    "react-doctor/nextjs-no-edge-og-runtime": "error",
    "react-doctor/nextjs-no-font-link": "error",
    "react-doctor/nextjs-no-google-analytics-script": "error",
    "react-doctor/nextjs-no-head-import": "error",
    "react-doctor/nextjs-no-img-element": "error",
    "react-doctor/nextjs-no-native-script": "error",
    "react-doctor/nextjs-no-polyfill-script": "error",
    "react-doctor/nextjs-no-redirect-in-try-catch": "error",
    "react-doctor/nextjs-no-script-in-head": "error",
    "react-doctor/nextjs-no-side-effect-in-get-handler": "error",
    "react-doctor/nextjs-no-use-search-params-without-suspense": "error",
    "react-doctor/nextjs-no-vercel-og-import": "error",
    // TanStack Query/Router/Start rules.
    "react-doctor/query-destructure-result": "error",
    "react-doctor/query-mutation-missing-invalidation": "error",
    "react-doctor/query-no-query-in-effect": "error",
    "react-doctor/query-no-rest-destructuring": "error",
    "react-doctor/query-no-usequery-for-mutation": "error",
    "react-doctor/query-no-void-query-fn": "error",
    "react-doctor/query-stable-query-client": "error",
    "react-doctor/tanstack-start-get-mutation": "error",
    "react-doctor/tanstack-start-loader-parallel-fetch": "error",
    "react-doctor/tanstack-start-missing-head-content": "error",
    "react-doctor/tanstack-start-no-anchor-element": "error",
    "react-doctor/tanstack-start-no-direct-fetch-in-loader": "error",
    "react-doctor/tanstack-start-no-dynamic-server-fn-import": "error",
    "react-doctor/tanstack-start-no-navigate-in-render": "error",
    "react-doctor/tanstack-start-no-secrets-in-loader": "error",
    "react-doctor/tanstack-start-no-use-server-in-handler": "error",
    "react-doctor/tanstack-start-no-useeffect-fetch": "error",
    "react-doctor/tanstack-start-redirect-in-try-catch": "error",
    "react-doctor/tanstack-start-route-property-order": "error",
    "react-doctor/tanstack-start-server-fn-method-order": "error",
    "react-doctor/tanstack-start-server-fn-validate-input": "error",
  },
});
