export default {
  // ESLint-Import: Static analysis
  'import/no-unresolved': 'off',
  'import/named': 'error',
  'import/default': 'error',
  'import/namespace': 'error',
  'import/no-restricted-paths': 'error',
  'import/no-absolute-path': 'error',
  'import/no-dynamic-require': 'error',
  'import/no-internal-modules': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/no-self-import': 'error',
  'import/no-cycle': 'error',
  'import/no-useless-path-segments': 'error',
  'import/no-relative-parent-imports': 'off',
  'import/no-relative-packages': 'error',

  // ESLint-Import: Helpful warnings
  'import/export': 'error',
  'import/no-named-as-default': 'off',
  'import/no-named-as-default-member': 'error',
  'import/no-deprecated': 'error',
  'import/no-extraneous-dependencies': 'error',
  'import/no-mutable-exports': 'error',
  'import/no-unused-modules': 'error',

  // ESLint-Import: Module systems
  'import/unambiguous': 'error',
  'import/no-commonjs': 'error',
  'import/no-amd': 'error',
  'import/no-nodejs-modules': 'error',
  'import/no-import-module-exports': 'error',

  // ESLint-Import: Style guide
  'import/first': 'error',
  'import/exports-last': 'off',
  'import/no-duplicates': 'error',
  'import/no-namespace': 'off',
  'import/extensions': 'off',
  'import/order': 'error',
  'import/newline-after-import': 'error',
  'import/prefer-default-export': 'off',
  'import/max-dependencies': 'off',
  'import/no-unassigned-import': 'off',
  'import/no-named-default': 'error',
  'import/no-default-export': 'off',
  'import/no-named-export': 'off',
  'import/no-anonymous-default-export': 'error',
  'import/group-exports': 'off',
  'import/dynamic-import-chunkname': 'error',
};