/* eslint-disable import/no-anonymous-default-export */

export default {
  // ESLint-n
  'n/handle-callback-err': 'error',
  'n/no-callback-literal': 'error',
  'n/no-exports-assign': 'error',
  'n/no-extraneous-import': 'error',
  'n/no-extraneous-require': 'error',
  'n/no-missing-import': 'off',
  'n/no-missing-require': 'error',
  'n/no-new-require': 'error',
  'n/no-path-concat': 'error',
  'n/no-process-exit': 'error',
  'n/no-unpublished-bin': 'error',
  'n/no-unpublished-import': 'error',
  'n/no-unpublished-require': 'error',
  'n/no-unsupported-features/es-builtins': 'off',
  'n/no-unsupported-features/es-syntax': 'off',
  'n/no-unsupported-features/node-builtins': 'off',
  'n/process-exit-as-throw': 'error',
  'n/shebang': 'error',
  'n/no-deprecated-api': 'error',
  'n/callback-return': 'error',
  'n/exports-style': 'error',
  'n/file-extension-in-import': 'off',
  'n/global-require': 'error',
  'n/no-mixed-requires': 'error',
  'n/no-process-env': 'off',
  'n/no-restricted-import': 'error',
  'n/no-restricted-require': 'error',
  'n/no-sync': 'error',
  'n/prefer-global/buffer': 'error',
  'n/prefer-global/console': 'error',
  'n/prefer-global/process': 'error',
  'n/prefer-global/text-decoder': 'error',
  'n/prefer-global/text-encoder': 'error',
  'n/prefer-global/url-search-params': 'error',
  'n/prefer-global/url': 'error',
  'n/prefer-promises/dns': 'error',
  'n/prefer-promises/fs': 'error',
};
