/* eslint-disable import/no-anonymous-default-export */

export default {
  // React-ESLint
  'react/boolean-prop-naming': 'error',
  'react/button-has-type': 'error',
  'react/default-props-match-prop-types': 'error',
  'react/destructuring-assignment': 'error',
  'react/display-name': 'error',
  'react/forbid-component-props': 'off',
  'react/forbid-dom-props': 'error',
  'react/forbid-elements': 'error',
  'react/forbid-foreign-prop-types': 'error',
  'react/forbid-prop-types': 'error',
  'react/function-component-definition': [
    'error',
    {
      namedComponents: 'arrow-function',
    },
  ],
  'react/no-access-state-in-setstate': 'error',
  'react/no-adjacent-inline-elements': 'error',
  'react/no-array-index-key': 'off',
  'react/no-arrow-function-lifecycle': 'off',
  'react/no-children-prop': 'error',
  'react/no-danger': 'error',
  'react/no-danger-with-children': 'error',
  'react/no-deprecated': 'error',
  'react/no-did-mount-set-state': 'error',
  'react/no-did-update-set-state': 'error',
  'react/no-direct-mutation-state': 'error',
  'react/no-find-dom-node': 'error',
  'react/no-invalid-html-attribute': 'off',
  'react/no-is-mounted': 'error',
  'react/no-multi-comp': 'off',
  'react/no-namespace': 'error',
  'react/no-redundant-should-component-update': 'error',
  'react/no-render-return-value': 'error',
  'react/no-set-state': 'error',
  'react/no-string-refs': 'error',
  'react/no-this-in-sfc': 'error',
  'react/no-typos': 'error',
  'react/no-unescaped-entities': 'error',
  'react/no-unsafe': 'error',
  'react/no-unstable-nested-components': 'error',
  'react/no-unused-class-component-methods': 'off',
  'react/no-unused-prop-types': 'error',
  'react/no-unused-state': 'error',
  'react/no-will-update-set-state': 'error',
  'react/prefer-es6-class': 'error',
  'react/prefer-exact-props': 'error',
  'react/prefer-read-only-props': 'error',
  'react/prefer-stateless-function': 'error',
  'react/prop-types': 'error',
  'react/react-in-jsx-scope': 'off',
  'react/require-default-props': 'off',
  'react/require-optimization': 'error',
  'react/require-render-return': 'error',
  'react/self-closing-comp': 'error',
  'react/sort-comp': 'error',
  'react/sort-prop-types': 'error',
  'react/state-in-constructor': 'error',
  'react/static-property-placement': 'error',
  'react/style-prop-object': 'error',
  'react/void-dom-elements-no-children': 'error',

  // React-ESLint JSX-Specific Rules
  'react/jsx-boolean-value': 'error',
  'react/jsx-curly-brace-presence': 'error',
  'react/jsx-filename-extension': [
    'error',
    {
      extensions: ['.tsx'],
    },
  ],
  'react/jsx-fragments': 'error',
  'react/jsx-handler-names': 'error',
  'react/jsx-key': 'error',
  'react/jsx-max-depth': 'off',
  'react/jsx-max-props-per-line': 'off',
  'react/jsx-newline': 'off',
  'react/jsx-no-bind': 'off',
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-duplicate-props': 'error',
  'react/jsx-no-literals': 'off',
  'react/jsx-no-script-url': 'error',
  'react/jsx-no-target-blank': 'error',
  'react/jsx-no-undef': 'error',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-one-expression-per-line': 'off',
  'react/jsx-pascal-case': 'error',
  'react/jsx-props-no-spreading': 'off',
  'react/jsx-sort-default-props': 'error',
  'react/jsx-sort-props': 'off',
  // Deprecated: "react/jsx-space-before-closing": "error",
  'react/jsx-uses-react': 'error',
  'react/jsx-uses-vars': 'error',
};
