import { defineConfig } from "oxlint";

// Runs eslint-plugin-sonarjs through oxlint's JS plugin support to close
// the gap with the ESLint preset. Rules that require type information are
// not supported by the JS plugin bridge and are excluded.
export default defineConfig({
  jsPlugins: [{ name: "sonarjs", specifier: "eslint-plugin-sonarjs" }],
  rules: {
    "sonarjs/arguments-usage": "error",
    "sonarjs/array-constructor": "error",
    // Fights the formatter (arrowParentheses: always).
    "sonarjs/arrow-function-convention": "off",
    "sonarjs/async-test-assertions": "error",
    "sonarjs/aws-apigateway-public-api": "error",
    "sonarjs/aws-ec2-rds-dms-public": "error",
    "sonarjs/aws-ec2-unencrypted-ebs-volume": "error",
    "sonarjs/aws-efs-unencrypted": "error",
    "sonarjs/aws-iam-all-privileges": "error",
    "sonarjs/aws-iam-all-resources-accessible": "error",
    "sonarjs/aws-iam-privilege-escalation": "error",
    "sonarjs/aws-iam-public-access": "error",
    "sonarjs/aws-opensearchservice-domain": "error",
    "sonarjs/aws-rds-unencrypted-databases": "error",
    "sonarjs/aws-restricted-ip-admin-access": "error",
    "sonarjs/aws-s3-bucket-granted-access": "error",
    "sonarjs/aws-s3-bucket-insecure-http": "error",
    "sonarjs/aws-s3-bucket-public-access": "error",
    "sonarjs/aws-s3-bucket-versioning": "error",
    "sonarjs/aws-sagemaker-unencrypted-notebook": "error",
    "sonarjs/aws-sns-unencrypted-topics": "error",
    "sonarjs/aws-sqs-unencrypted-queue": "error",
    "sonarjs/block-scoped-var": "error",
    "sonarjs/bool-param-default": "error",
    "sonarjs/call-argument-line": "error",
    "sonarjs/chai-determinate-assertion": "error",
    "sonarjs/class-name": "error",
    "sonarjs/code-eval": "error",
    // Matches Biome's noExcessiveCognitiveComplexity limit.
    "sonarjs/cognitive-complexity": ["error", 20],
    "sonarjs/comma-or-logical-or-case": "error",
    "sonarjs/comment-regex": "error",
    "sonarjs/constructor-for-side-effects": "error",
    "sonarjs/content-length": "error",
    "sonarjs/content-security-policy": "error",
    "sonarjs/cookie-no-httponly": "error",
    "sonarjs/cors": "error",
    "sonarjs/csrf": "error",
    // Duplicate of the core complexity rule.
    "sonarjs/cyclomatic-complexity": "off",
    "sonarjs/declarations-in-global-scope": "error",
    "sonarjs/destructuring-assignment-syntax": "error",
    "sonarjs/disabled-timeout": "error",
    "sonarjs/dynamically-constructed-templates": "error",
    // Mirrors the ESLint preset.
    "sonarjs/elseif-without-else": "off",
    "sonarjs/encryption-secure-mode": "error",
    "sonarjs/expression-complexity": "error",
    // Requires a headerFormat option; errors on every file without one.
    "sonarjs/file-header": "off",
    "sonarjs/file-name-differ-from-class": "error",
    "sonarjs/file-permissions": "error",
    "sonarjs/file-uploads": "error",
    "sonarjs/fixme-tag": "error",
    "sonarjs/for-in": "error",
    "sonarjs/for-loop-increment-sign": "error",
    "sonarjs/function-inside-loop": "error",
    "sonarjs/function-name": "error",
    "sonarjs/future-reserved-words": "error",
    "sonarjs/generator-without-yield": "error",
    "sonarjs/hardcoded-secret-signatures": "error",
    "sonarjs/hashing": "error",
    "sonarjs/hooks-before-test-cases": "error",
    "sonarjs/inconsistent-function-call": "error",
    "sonarjs/insecure-cookie": "error",
    "sonarjs/insecure-jwt-token": "error",
    "sonarjs/inverted-assertion-arguments": "error",
    "sonarjs/label-position": "error",
    "sonarjs/link-with-target-blank": "error",
    // The preset disables max-lines everywhere.
    "sonarjs/max-lines": "off",
    // The preset disables max-lines-per-function everywhere.
    "sonarjs/max-lines-per-function": "off",
    "sonarjs/max-switch-cases": "error",
    "sonarjs/max-union-size": "error",
    "sonarjs/misplaced-loop-counter": "error",
    // Duplicate of max-depth, which is off.
    "sonarjs/nested-control-flow": "off",
    "sonarjs/no-all-duplicated-branches": "error",
    "sonarjs/no-angular-bypass-sanitization": "error",
    "sonarjs/no-built-in-override": "error",
    "sonarjs/no-case-label-in-switch": "error",
    "sonarjs/no-clear-text-protocols": "error",
    "sonarjs/no-code-after-done": "error",
    "sonarjs/no-collapsible-if": "error",
    "sonarjs/no-commented-code": "error",
    "sonarjs/no-dead-store": "error",
    "sonarjs/no-delete-var": "error",
    "sonarjs/no-duplicate-in-composite": "error",
    "sonarjs/no-duplicate-string": "error",
    "sonarjs/no-duplicate-test-title": "error",
    "sonarjs/no-duplicated-branches": "error",
    "sonarjs/no-element-overwrite": "error",
    "sonarjs/no-empty-collection": "error",
    "sonarjs/no-empty-test-file": "error",
    "sonarjs/no-empty-test-title": "error",
    "sonarjs/no-equals-in-for-termination": "error",
    "sonarjs/no-exclusive-tests": "error",
    "sonarjs/no-extra-arguments": "error",
    "sonarjs/no-fallthrough": "error",
    "sonarjs/no-floating-point-equality": "error",
    "sonarjs/no-forced-browser-interaction": "error",
    "sonarjs/no-function-declaration-in-block": "error",
    "sonarjs/no-global-this": "error",
    "sonarjs/no-globals-shadowing": "error",
    "sonarjs/no-gratuitous-expressions": "error",
    "sonarjs/no-hardcoded-ip": "error",
    "sonarjs/no-hardcoded-passwords": "error",
    "sonarjs/no-hardcoded-secrets": "error",
    "sonarjs/no-hook-setter-in-body": "error",
    "sonarjs/no-identical-conditions": "error",
    "sonarjs/no-identical-expressions": "error",
    "sonarjs/no-identical-functions": "error",
    "sonarjs/no-ignored-exceptions": "error",
    "sonarjs/no-implicit-dependencies": "error",
    "sonarjs/no-implicit-global": "error",
    "sonarjs/no-incomplete-assertions": "error",
    "sonarjs/no-internal-api-use": "error",
    "sonarjs/no-invariant-returns": "error",
    "sonarjs/no-inverted-boolean-check": "error",
    "sonarjs/no-labels": "error",
    "sonarjs/no-literal-call": "error",
    "sonarjs/no-mime-sniff": "error",
    "sonarjs/no-nested-assignment": "error",
    "sonarjs/no-nested-conditional": "error",
    "sonarjs/no-nested-functions": "error",
    "sonarjs/no-nested-incdec": "error",
    "sonarjs/no-nested-switch": "error",
    "sonarjs/no-nested-template-literals": "error",
    "sonarjs/no-os-command-from-path": "error",
    "sonarjs/no-parameter-reassignment": "error",
    "sonarjs/no-primitive-wrappers": "error",
    "sonarjs/no-redundant-assignments": "error",
    "sonarjs/no-redundant-boolean": "error",
    "sonarjs/no-redundant-jump": "error",
    // The jsPlugins bridge provides no globals, so every identifier is flagged.
    "sonarjs/no-reference-error": "off",
    "sonarjs/no-referrer-policy": "error",
    "sonarjs/no-same-argument-assert": "error",
    "sonarjs/no-same-line-conditional": "error",
    "sonarjs/no-session-cookies-on-static-assets": "error",
    "sonarjs/no-skipped-tests": "error",
    "sonarjs/no-sonar-comments": "error",
    "sonarjs/no-table-as-layout": "error",
    "sonarjs/no-trivial-assertions": "error",
    "sonarjs/no-undefined-assignment": "error",
    "sonarjs/no-unenclosed-multiline-block": "error",
    "sonarjs/no-uniq-key": "error",
    "sonarjs/no-unthrown-error": "error",
    "sonarjs/no-unused-collection": "error",
    "sonarjs/no-unused-function-argument": "error",
    "sonarjs/no-unused-vars": "error",
    "sonarjs/no-use-of-empty-return-value": "error",
    "sonarjs/no-useless-catch": "error",
    "sonarjs/no-useless-increment": "error",
    "sonarjs/no-useless-react-setstate": "error",
    "sonarjs/no-variable-usage-before-declaration": "error",
    "sonarjs/no-weak-cipher": "error",
    "sonarjs/no-weak-keys": "error",
    "sonarjs/no-wildcard-import": "error",
    "sonarjs/non-existent-operator": "error",
    "sonarjs/object-alt-content": "error",
    "sonarjs/prefer-default-last": "error",
    "sonarjs/prefer-object-literal": "error",
    "sonarjs/prefer-promise-shorthand": "error",
    "sonarjs/prefer-single-boolean-return": "error",
    "sonarjs/prefer-specific-assertions": "error",
    "sonarjs/prefer-type-guard": "error",
    "sonarjs/prefer-while": "error",
    "sonarjs/production-debug": "error",
    "sonarjs/pseudo-random": "error",
    "sonarjs/public-static-readonly": "error",
    "sonarjs/publicly-writable-directories": "error",
    "sonarjs/redundant-type-aliases": "error",
    "sonarjs/review-blockchain-mnemonic": "error",
    "sonarjs/session-regeneration": "error",
    // Conflicts with sort-keys.
    "sonarjs/shorthand-property-grouping": "off",
    "sonarjs/stable-tests": "error",
    "sonarjs/stateful-regex": "error",
    "sonarjs/strict-transport-security": "error",
    "sonarjs/super-linear-regex": "error",
    "sonarjs/table-header": "error",
    "sonarjs/table-header-reference": "error",
    "sonarjs/test-check-exception": "error",
    "sonarjs/todo-tag": "error",
    "sonarjs/too-many-break-or-continue-in-loop": "error",
    "sonarjs/unverified-certificate": "error",
    "sonarjs/unverified-hostname": "error",
    "sonarjs/updated-const-var": "error",
    "sonarjs/updated-loop-counter": "error",
    "sonarjs/use-type-alias": "error",
    "sonarjs/variable-name": "error",
    "sonarjs/weak-ssl": "error",
    "sonarjs/x-powered-by": "error",
    "sonarjs/xml-parser-xxe": "error",
  },
});
